theme: jekyll-theme-minimal
title: Ahmedkayd's homepage
description: Bookmark this to keep an eye on my project updates!

layout: page
title: "About Us"
permalink:  github.com/ahmedkayd/ahmedkayd.github.io/blob/main/about.md